import Link from "next/link";
import { CATALOG } from "@/lib/catalog";

export default function HomePage() {
  return <div className="overflow-hidden">
    <section className="relative max-w-6xl mx-auto px-5 sm:px-8 pt-16 pb-20 lg:pt-24 lg:pb-28">
      <div className="absolute -top-24 right-[-8rem] h-96 w-96 rounded-full bg-brand-500/10 blur-3xl" />
      <div className="relative grid lg:grid-cols-[1.1fr_.9fr] gap-12 items-center">
        <div><div className="inline-flex items-center gap-2 rounded-full border border-brand-500/30 bg-brand-500/10 px-3 py-1 text-xs font-semibold tracking-wide text-brand-500">YOUR TASTE, CONNECTED <span>✦</span></div>
          <h1 className="mt-5 max-w-2xl text-5xl sm:text-6xl font-black tracking-[-0.055em] leading-[.95] text-ink-300">Everything you love.<br /><span className="text-brand-500">One living profile.</span></h1>
          <p className="mt-6 max-w-xl text-lg leading-8 text-ink-400">TasteStack is your personal culture shelf. Track the anime you&apos;re watching, films you&apos;ve loved, games you&apos;ve finished, albums on repeat, and books still calling your name.</p>
          <div className="mt-8 flex flex-wrap gap-3"><Link href="/signup" className="btn-primary text-base px-5 py-3">Start your stack <span>→</span></Link><Link href="/discover" className="btn-secondary text-base px-5 py-3">Explore picks</Link></div>
          <div className="mt-9 flex items-center gap-5 text-sm text-ink-500"><span><b className="text-ink-300">7</b> media worlds</span><span className="h-4 w-px bg-ink-700"/><span><b className="text-ink-300">1</b> shareable identity</span></div></div>
        <div className="relative mx-auto w-full max-w-md"><div className="absolute inset-7 rounded-[2rem] bg-brand-500/15 blur-2xl" /><div className="relative rotate-[2deg] rounded-3xl border border-ink-700 bg-ink-900 p-5 shadow-2xl"><div className="flex items-center gap-3 border-b border-ink-800 pb-4"><div className="h-11 w-11 rounded-xl bg-gradient-to-br from-brand-500 to-violet-500 grid place-items-center text-lg font-bold text-white">T</div><div><p className="font-bold text-ink-300">your-taste-stack</p><p className="text-xs text-ink-500">A life in lists</p></div><span className="ml-auto rounded-full bg-success/15 px-2.5 py-1 text-xs font-semibold text-success">Public</span></div><div className="mt-5 grid grid-cols-4 gap-2">{CATALOG.slice(0, 8).map((item) => <div key={item.apiId} className="aspect-[3/4] rounded-lg border border-white/10 p-2 flex items-end text-lg" style={{ background: `linear-gradient(145deg, ${item.accent}, #14202c 88%)` }}><span>{item.cover}</span></div>)}</div><div className="mt-5 grid grid-cols-3 gap-3 text-center"><div><p className="text-xl font-black text-ink-300">48</p><p className="text-xs text-ink-500">tracked</p></div><div><p className="text-xl font-black text-ink-300">16</p><p className="text-xs text-ink-500">favourites</p></div><div><p className="text-xl font-black text-ink-300">5</p><p className="text-xs text-ink-500">worlds</p></div></div></div></div>
      </div>
    </section>
    <section className="border-y border-ink-800 bg-ink-900/40"><div className="max-w-6xl mx-auto px-5 sm:px-8 py-16"><div className="max-w-xl"><p className="text-xs font-bold tracking-[.18em] text-brand-500">DESIGNED FOR OBSESSIVES</p><h2 className="mt-3 text-3xl font-black tracking-tight">A home for every rabbit hole.</h2></div><div className="mt-9 grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{[["✦","Anime & manga","Your seasonal queue and all-time canon."],["▶","Film & television","Keep a beautiful watch history."],["♜","Games","Remember every world you stepped into."],["♫","Music & books","Save the things that changed your week."]].map(([icon,title,body])=><div key={title} className="card p-5"><div className="text-2xl text-brand-500">{icon}</div><h3 className="mt-5 font-bold text-ink-300">{title}</h3><p className="mt-2 text-sm leading-6 text-ink-500">{body}</p></div>)}</div></div></section>
    <section className="max-w-6xl mx-auto px-5 sm:px-8 py-20 text-center"><p className="text-brand-500 font-semibold text-sm">MAKE YOUR TASTE DISCOVERABLE</p><h2 className="mt-3 text-3xl sm:text-4xl font-black tracking-tight">The profile link you&apos;ll actually want to share.</h2><p className="mt-4 mx-auto max-w-lg text-ink-500">Add a title, give it a score, mark your progress, and let your profile tell the story.</p><Link href="/signup" className="btn-primary mt-8 px-6 py-3">Create a free profile</Link></section>
  </div>;
}
